import {
  type LucideIcon,
  type LucideProps,
  Home,
  Layers,
  GitBranch,
  Wrench,
  Mail,
  Code,
  Notebook,
  Braces,
  FileCode2,
  Cpu,
  CircuitBoard,
  Database,
  Atom,
  Split,
  GitMerge,
  Boxes,
  Server,
  Route,
  DatabaseZap,
  Leaf,
  Triangle,
  Wind,
  ArrowLeftRight,
  Container,
  Terminal,
  Rocket,
  Cloud,
  Zap,
  CloudCog,
  Gauge,
  Coffee,
  HardDrive,
  TextCursor,
  Award,
  TerminalSquare,
  HelpCircle,
} from "lucide-react";

const iconRegistry = {
  home: Home,
  layers: Layers,
  "git-branch": GitBranch,
  wrench: Wrench,
  mail: Mail,
  code: Code,
  notebook: Notebook,
  award: Award,
  "terminal-square": TerminalSquare,
  Braces,
  FileCode2,
  Cpu,
  CircuitBoard,
  Database,
  Atom,
  Split,
  GitMerge,
  Boxes,
  Server,
  Route,
  DatabaseZap,
  Leaf,
  Triangle,
  Wind,
  ArrowLeftRight,
  Container,
  Terminal,
  Rocket,
  Cloud,
  Zap,
  CloudCog,
  Gauge,
  Coffee,
  HardDrive,
  TextCursor,
  Award,
  TerminalSquare,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const Component = iconRegistry[name as IconName] ?? HelpCircle;
  return <Component {...props} />;
}
